### PR TITLE
Fix icelake features

### PR DESCRIPTION
**Pull request by michaelkuhn**
Some of the feature flags are named differently and clwb is missing on
my i7-1065G7. See https://github.com/spack/spack/pull/18151.

cc @alalazo

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Review by alalazo — CHANGES_REQUESTED** [review]
Apologies for being too quick to approve. I think we should investigate the absence of `clwb` (which I missed in the previous PR on Spack).  The reason is that GCC mentions that instruction set explicitly when activating optimizations:
```
           icelake-client
               Intel Icelake Client CPU with 64-bit extensions, MOVBE, MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, POPCNT, PKU, AVX, AVX2,
               AES, PCLMUL, FSGSBASE, RDRND, FMA, BMI, BMI2, F16C, RDSEED, ADCX, PREFETCHW, CLFLUSHOPT, XSAVEC, XSAVES, AVX512F, AVX512VL,
               AVX512BW, AVX512DQ, AVX512CD, AVX512VBMI, AVX512IFMA, SHA, CLWB, UMIP, RDPID, GFNI, AVX512VBMI2, AVX512VPOPCNTDQ, AVX512BITALG,
               AVX512VNNI, VPCLMULQDQ, VAES instruction set support.

```

**Comment by alalazo** [comment]
The CLWB instruction is explicitly mentioned in [wikichip](https://en.wikichip.org/wiki/intel/microarchitectures/ice_lake_(client))

**Comment by michaelkuhn** [comment]
The Intel manual also states that it should be available on Ice Lake Client. Maybe my CPU does not support it since it's a mobile one?

**Comment by alalazo** [comment]
@michaelkuhn Can you update this to restore `clwb`? I think we can get the fix in feature names in and keep investigating the presence / absence of `clwb` in some models.

**Comment by michaelkuhn** [comment]
Sure, I pushed a new version with `clwb` restored.

**Review by alalazo — APPROVED** [review]
Thanks @micha

**Comment by boegel** [comment]
@alalazo better open an issue to follow up on the `clwb` part?

**Comment by alalazo** [comment]
Sure, I'll open it today.

**Pull request merged**
