### PR TITLE
Add definition of Neoverse N2 features

### PR DESCRIPTION
**Pull request by paolotricerri**
This patch should address https://github.com/archspec/archspec-json/issues/97

### CODE REVIEW

**Comment by paolotricerri** [comment]
How can I invite a colleague (username @dslarm) to the review?

**Comment by alalazo** [comment]
@paolotricerri Anybody can leave a review, as far as I know - so should be fine to just ping them. For the "Reviewers" list in the PR I guess you need to have more rights on the upstream repository.

**Comment by alalazo** [comment]
Can you give a more descriptive title, and explain in the description how this solves the issue?

**Comment by alalazo** [comment]
Closing in favor of #112

**Pull request closed without merging**
