### PR TITLE
Remove `sm3`, `*sm4` from `neoverse_v*`

### LINKED ISSUE #102: Neoverse V2 detected as Neoverse N1
The V2 is unfortunately still misidentifying due to feature set differences.

The Cryptographic extension to arm architecture is an optional/configuration featureset for the V2 core.
From https://developer.arm.com/documentation/102375/latest/ - page 30

``The Neoverse™ V2 core configuration options include:
Cryptographic Extension
You can configure your implementation with or without the Cryptographic Extension.
[..]
Random Number Generator
You can configure your implementation with or without support for Armv8.5-RNG.``

* Crypto: it's possible for all of crypto extensions, or just SM crypto, to be disabled.  Assuming AES, SHA* are too prevalent to be disabled, this means sm3, sm4, svesm4.

* RNG:  Those would be the 'rng' instruction (already removed from the json - so we are good).

### PR DESCRIPTION
**Pull request by alalazo**
fixes #102
closes #106

### CODE REVIEW

**Comment by alalazo** [comment]
@paolotricerri FYI If you have the opportunity to get more samples of `proc/cpuinfo` those will be useful for tests. The one I added here is based on https://github.com/archspec/archspec-json/pull/106#issuecomment-2178848817

**Comment by paolotricerri** [comment]
Another question for @dslarm  is: while I was adding a sample for neoverse_v2 in the test files, I noticed that the existing neoverse_v2 sample does not contain some features that are instead included in the list of features posted by @dslarm above. 

The set of features **not** included in the current sample but that there are in the list above are:  **paca pacg rng bti**

I might be wrong but is it reasonable to think that all the neoverse_v2 samples in the test folder should be consistent with each other in terms of the features, apart from the crypto ones that this PR wants to remove? @alalazo @dslarm

**Comment by alalazo** [comment]
@paolotricerri See discussion in https://github.com/archspec/archspec-json/issues/83

**Comment by paolotricerri** [comment]
> @paolotricerri See discussion in #83

Thanks you! Then they can be removed. Thanks

**Comment by alalazo** [comment]
`paca`, `pacg` etc. are not used for detection, but I would leave them in the test files. Basically, test files should be pristine samples of real systems.

**Comment by paolotricerri** [comment]
Hi @alalazo , I had a chat with @dslarm and he confirmed that we can remove the Crypto features from Neoverse V1 and Neoverse V2. Thanks

**Comment by alalazo** [comment]
> I'll push a commit on this branch that removes them for both Neoverse, if you don't disagree.

@paolotricerri This PR already removes the features from `neoverse_v1` and neoverse_v2`. Or do you want some other modification?

**Comment by paolotricerri** [comment]
No @alalazo , sorry would have noticed that when cloning the code. No, that is all. Thanks a lot

**Pull request merged**
