### PR TITLE
Update spack to autodetect 4th Generation AMD EPYC processor or zen4

### PR DESCRIPTION
**Pull request by amd-toolchain-support**
Updated with flags info which will help spack to autodetect zen4

Please note, https://github.com/spack/spack/pull/33833 is the review request for AOCC-4.0.0

### CODE REVIEW

**Review by alalazo — CHANGES_REQUESTED** [review]
Can you add a one cpu sample of `/proc/cpuinfo` under tests, and maybe compiler flags for `gcc` and `clang`?

**Comment by alalazo** [comment]
@amd-toolchain-support

**Comment by alalazo** [comment]
@amd-toolchain-support Is this still of interest to you?

**Comment by amd-toolchain-support** [comment]
Apologies for the delayed response. We are having a few changes in PRs related to Zen4. Please give us some time. Meanwhile we'll mark this PR as draft.

**Comment by amd-toolchain-support** [comment]
> Can you add a one cpu sample of `/proc/cpuinfo` under tests, and maybe compiler flags for `gcc` and `clang`?

-- /proc/cpuinfo snip--
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 25
model		: 17
model name	: AMD EPYC 9654 96-Core Processor
stepping	: 1
microcode	: 0xa10110d
cpu MHz		: 2400.000
cache size	: 1024 KB
physical id	: 0
siblings	: 96
core id		: 0
cpu cores	: 96
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid overflow_recov succor smca fsrm flush_l1d sme sev sev_es
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 4792.38
TLB size	: 3584 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 52 bits physical, 57 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]

--snip end--

**Comment by amd-toolchain-support** [comment]
> Can you add a one cpu sample of `/proc/cpuinfo` under tests, and maybe compiler flags for `gcc` and `clang`?

- Added sample of `/proc/cpuinfo` under following file "tests/targets/linux-ubuntu20.04-zen4"
- Added compiler flags for `gcc` and `clang`

**Review by alalazo — APPROVED** [review]

**Comment by victorapm** [comment]
@amd-toolchain-support @alalazo  Are there plans to add `zen5` support soon? Thank you!

**Pull request merged**
