### PR TITLE
Neoverse V2: remove `sm3`, `sm4` and `svesm4`

### LINKED ISSUE #102: Neoverse V2 detected as Neoverse N1
The V2 is unfortunately still misidentifying due to feature set differences.

The Cryptographic extension to arm architecture is an optional/configuration featureset for the V2 core.
From https://developer.arm.com/documentation/102375/latest/ - page 30

``The Neoverse™ V2 core configuration options include:
Cryptographic Extension
You can configure your implementation with or without the Cryptographic Extension.
[..]
Random Number Generator
You can configure your implementation with or without support for Armv8.5-RNG.``

* Crypto: it's possible for all of crypto extensions, or just SM crypto, to be disabled.  Assuming AES, SHA* are too prevalent to be disabled, this means sm3, sm4, svesm4.

* RNG:  Those would be the 'rng' instruction (already removed from the json - so we are good).

### PR DESCRIPTION
**Pull request by paolotricerri**
fixes #102

### CODE REVIEW

**Comment by paolotricerri** [comment]
@dslarm

**Comment by giordano** [comment]
Can you please edit the title of the PR to be self descriptive? Just referencing an issue number isn't useful.

**Comment by alalazo** [comment]
> Can you please edit the title of the PR to be self descriptive? Just referencing an issue number isn't useful.

Asked the same thing in #105 A brief description of the PR would be welcome too.

**Comment by dslarm** [comment]
I can confirm that this patch fixes my initial issue: the sm2/3 and svesm4 are not present on the V2 system that I am using.  with this patch, 
`oetry run python
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import archspec.cpu
>>> print (archspec.cpu.host())
neoverse_v2
>>> 
`


and neoverse_n1 without it.

**Comment by alalazo** [comment]
Can you add a sample of the misidentified cpu to the tests?

**Comment by dslarm** [comment]
> Can you add a sample of the misidentified cpu to the tests? This would allow us to unit test this failed detection in `archspec`

@alalazo - this is the flags excerpt from cpuinfo:

    Flags:              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asim
                        dhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha51
                        2 sve asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpo
                        dp sve2 sveaes svepmull svebitperm svesha3 flagm2 frint svei
                        8mm svebf16 i8mm bf16 dgh rng bti

**Comment by paolotricerri** [comment]
Hi @alalazo,
It should be safe to remove these flags from Neoverse V2 now because of the test on cpuid I propose in another PR.

What do you think?

Thanks
P

**Review by alalazo — CHANGES_REQUESTED** [review]
@paolotricerri I think using `cpuid` is the way to disambiguate. On https://github.com/archspec/archspec-json/pull/106#issuecomment-2178848817, can you add a relevant sample of `/proc/cpuinfo` as done, for instance in:

- https://github.com/archspec/archspec-json/blob/master/tests/targets/linux-amazon-neoverse_v1

?

**Comment by paolotricerri** [comment]
@alalazo , in the test folder I already see a file with data for the neoverse_V2 case. That example has got the feature that this patch is trying to remove. Do you mean adding another one taking the features from the comment above https://github.com/archspec/archspec-json/pull/106#issuecomment-2178848817  ?

**Comment by alalazo** [comment]
> Do you mean adding another one taking the features from the comment above https://github.com/archspec/archspec-json/pull/106#issuecomment-2178848817 ?

Yes, they would be both two real cases of `neoverse_v2` that we need to detect.

**Comment by alalazo** [comment]
@paolotricerri Can you add a sample of `/proc/cpuinfo` for the Neoverse V2 without the crypto features?

**Review by alalazo — CHANGES_REQUESTED** [review]
Another consideration: do we need to remove `sm3` and `sm4` also from `noeverse-v1`? I would assume so, but seeking confirmation @dslarm

**Comment by paolotricerri** [comment]
Another question for @dslarm  is: while I was adding a sample for neoverse_v2 in the test files, I noticed that the existing neoverse_v2 sample does not contain some features that are instead included in the list of features posted by @dslarm above. 

The set of features **not** included in the current sample but that there are in the list above are:  **paca pacg rng bti**

I might be wrong but is it reasonable to think that all the neoverse_v2 samples in the test folder should be consistent with each other in terms of the features, apart from the crypto ones that this PR wants to remove? @alalazo @dslarm

**Pull request closed without merging**
