### PR TITLE
Add features for `m1`

### PR DESCRIPTION
**Pull request by giordano**
I simply copied the list of features in `/proc/cpuinfo`.  I verified that with this change I can still detect the CPU correctly:
```console
$ poetry run python -c "import archspec.cpu; print(archspec.cpu.host())"
m1
```
Let me know if I need to do anything else.

### CODE REVIEW

**Comment by alalazo** [comment]
I don't have access to an Apple M1, but I thought that macOS didn't provide any `/proc/cpuinfo` file? Currently we use output of `sysctl` to detect microarchitectures on `darwin` platforms.

**Comment by giordano** [comment]
I did this on Linux, not macOS :slightly_smiling_face:

**Comment by alalazo** [comment]
> I did this on Linux, not macOS

Fair enough. I guess I have a mental block that makes installing Linux on a Mac inconceivable for me :laughing: Can you also submit a sample of your `/proc/cpuinfo` file? You can find examples under the [tests/targets](https://github.com/archspec/archspec-json/tree/master/tests/targets) directory.

**Comment by giordano** [comment]
Done!

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Thanks!

**Pull request merged**
