### PR TITLE
updated additions for nvhpc compilers

### PR DESCRIPTION
**Pull request by cparrott73**
I have reworked these based on feedback from the archspec maintainers.

### CODE REVIEW

**Comment by cparrott73** [comment]
Hold on, I'm aware of the JSON failures, working on a fix.

**Comment by alalazo** [comment]
@cparrott73 Can you please rebase?
@glennpj Would you have some time to test drive this one again?

**Comment by alalazo** [comment]
Uh, what happened here?

**Comment by cparrott73** [comment]
Sorry - I must have botched this somehow.  I am not very experienced with git and was trying to figure out how to rebase and merge my changes.  I will respin this.

**Comment by alalazo** [comment]
@cparrott73 You can push to the same branch on your repo, and use that instead of `master` to submit the PR. Also, any change you do to your repo can be force pushed in case of errors - so no need to reopen PRs in general. Let me know if you need further help :slightly_smiling_face:

**Pull request closed without merging**
